# Generated by Django 2.0.2 on 2018-02-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='guesses_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
