# Generated by Django 2.0.2 on 2018-02-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0002_secret_guesses_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='success_state',
            field=models.IntegerField(default=0),
        ),
    ]
