# Generated by Django 2.0.2 on 2018-02-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0003_secret_success_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='game_status',
            field=models.IntegerField(default=0),
        ),
    ]
