# Generated by Django 2.0.2 on 2018-03-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0005_auto_20180225_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='hints_remaining',
            field=models.IntegerField(default=2),
        ),
    ]
